name: Deploy

on:
  push:
    branches:
      - main


env:
  DEP_PATH: requirements.txt

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@v1.0.5
