version: '1'
services: 
  chatbot:
    image: comp7940-group6-chatbot
    environment:
      - ACCESS_TOKEN=5288928403:AAEUkBF6wjh7zYUVH-jfjNkcmcjL9n_9la0
      - HOST=redis
      - PASSWORD=comp7940passwordlab8
      - REDISPORT=6379
    command: python chatbot.py
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]