name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: 21415315
        DOCKER_PASSWORD: 19940823Hrj_
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 21415315/comp7940-group6-chatbot:$(date +%s)
      
    - name: Docker Push
      run: docker push 21415315/comp7940-group6-chatbot
